CREATE TABLE IF NOT EXISTS users(
    id BIGINT PRIMARY KEY NOT NULL,
    username VARCHAR(24) NOT NULL,
    role SMALLINT DEFAULT 0,
    avatar_hash VARCHAR(32) DEFAULT NULL,
    password_hash VARCHAR(120) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    locale_code VARCHAR(5) DEFAULT 'en_US'
);
CREATE TABLE IF NOT EXISTS text_channels(
    id BIGINT PRIMARY KEY NOT NULL,
    name VARCHAR(24) NOT NULL,
    description VARCHAR(128) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS messages(
    id BIGINT PRIMARY KEY NOT NULL,
    channel_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);